blank_issues_enabled: false

contact_links:
  - name: ğŸ§  Ground Issue Role í…œí”Œë¦¿
    url: https://github.com/Fin-N-AI/FinNAI/issues/new?template=ground_issue_role.yml
    about: ê¸°ëŠ¥ ì¶”ê°€, ìˆ˜ì •, ì‚­ì œ ë“± íŒ€ ìš´ì˜ ê´€ë ¨ ì´ìŠˆë¥¼ ë“±ë¡í•˜ë ¤ë©´ í´ë¦­í•˜ì„¸ìš”.
